name: PhantomVoteSkip
version: '69.420'
main: fun.aqurik.phantomVoteSkip.PhantomVoteSkip
api-version: '1.21'
authors: [ Aqurik13 ]
description: Йоуйоуйоу, супер крутой и эпичный плагин на куличи
website: https://aqurik.fun
